#!/usr/bin/env python3
"""Validate the skills repository. Run from anywhere: python3 scripts/validate_skills.py

Checks:
  1. every skills/*/scripts/*.py that offers --self-test passes it, normally and under `python -O`;
  2. every relative Markdown link in README.md and skills/**/*.md resolves, including #anchors;
  3. every skills/*/SKILL.md has YAML frontmatter with `name` (equal to its directory, [a-z0-9-]) and a
     non-empty `description` of at most 1024 characters;
  4. every skill has agents/openai.yaml with interface.display_name, short_description and a
     default_prompt that names the skill as $<skill-name>;
  5. no absolute user-home paths (/Users/<name>, C:\\Users\\<name>) or project checkout paths leak into the skills;
  6. no vendor model text is embedded in scripts, model files or fenced code (licence markers, or
     .subckt/.model cards larger than a short illustrative example).
Standard library only. Exit status 1 on any failure.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
PATH_LEAK = re.compile(r"/Users/[A-Za-z]|[A-Za-z]:\\Users\\|yellow-punch/")   # container paths such as /home/build are fine
VENDOR_MARKERS = re.compile(r"all rights reserved|model generated by|pspice model editor|commercial use or resale", re.I)
MODEL_FILES = {".lib", ".mod", ".cir", ".sp", ".spi", ".inc", ".py", ".cpp", ".hpp", ".txt"}
MAX_SUBCKT_LINES, MAX_MODEL_PARAMS = 25, 12


def anchors(path: Path) -> set[str]:
    out = set()
    text = re.sub(r"```.*?```", "", path.read_text(encoding="utf-8"), flags=re.S)
    for line in text.split("\n"):
        m = re.match(r"^#+\s+(.*)", line)
        if m:
            out.add(re.sub(r"[^\w\s-]", "", m.group(1).strip().lower()).replace(" ", "-"))
    return out


def check_links(problems: list[str]) -> int:
    count = 0
    for md in [ROOT / "README.md", *sorted(SKILLS.rglob("*.md"))]:
        text = re.sub(r"```.*?```", "", md.read_text(encoding="utf-8"), flags=re.S)
        for m in re.finditer(r"\]\(([^)\s]+)\)", text):
            link = m.group(1)
            if link.startswith(("http://", "https://", "mailto:")):
                continue
            count += 1
            path, _, anchor = link.partition("#")
            target = (md.parent / path).resolve() if path else md
            if not target.exists():
                problems.append(f"broken link {md.relative_to(ROOT)} -> {link}")
            elif anchor and target.suffix == ".md" and anchor not in anchors(target):
                problems.append(f"broken anchor {md.relative_to(ROOT)} -> {link}")
    return count


def check_frontmatter(skill: Path, problems: list[str]) -> None:
    text = (skill / "SKILL.md").read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        problems.append(f"{skill.name}/SKILL.md: missing YAML frontmatter")
        return
    fields = dict(re.findall(r"^([a-z_]+):\s*(.*)$", m.group(1), re.M))
    if fields.get("name") != skill.name or not re.fullmatch(r"[a-z0-9-]+", fields.get("name", "")):
        problems.append(f"{skill.name}/SKILL.md: name {fields.get('name')!r} must equal the directory name")
    desc = fields.get("description", "").strip()
    if not desc:
        problems.append(f"{skill.name}/SKILL.md: empty description")
    elif len(desc) > 1024:
        problems.append(f"{skill.name}/SKILL.md: description is {len(desc)} characters (max 1024)")


def check_agent_yaml(skill: Path, problems: list[str]) -> None:
    path = skill / "agents" / "openai.yaml"
    if not path.is_file():
        problems.append(f"{skill.name}: agents/openai.yaml missing")
        return
    text = path.read_text(encoding="utf-8")
    if not re.search(r"^interface:\s*$", text, re.M):
        problems.append(f"{skill.name}/agents/openai.yaml: no top-level 'interface:' mapping")
    for key in ("display_name", "short_description", "default_prompt"):
        m = re.search(rf'^\s+{key}:\s*"(.+)"\s*$', text, re.M)
        if not m:
            problems.append(f"{skill.name}/agents/openai.yaml: {key} missing or not a quoted string")
        elif key == "default_prompt" and f"${skill.name}" not in m.group(1):
            problems.append(f"{skill.name}/agents/openai.yaml: default_prompt does not mention ${skill.name}")


def code_regions(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    if path.suffix == ".md":
        return re.findall(r"```.*?```", text, flags=re.S)
    return [text] if path.suffix in MODEL_FILES else []


def check_leaks(problems: list[str]) -> None:
    for path in [ROOT / "README.md", *sorted(p for p in SKILLS.rglob("*") if p.is_file())]:
        if path.suffix in {".png", ".jpg", ".jpeg", ".glb", ".blend", ".ico"}:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for n, line in enumerate(text.split("\n"), 1):
            if PATH_LEAK.search(line):
                problems.append(f"absolute or project path in {path.relative_to(ROOT)}:{n}")
        for region in code_regions(path):
            if VENDOR_MARKERS.search(region):
                problems.append(f"licence marker inside code/model text in {path.relative_to(ROOT)}")
            lines = region.split("\n")
            for i, line in enumerate(lines):
                if re.match(r"\s*\.subckt\b", line, re.I):
                    end = next((j for j in range(i, len(lines)) if re.match(r"\s*\.ends\b", lines[j], re.I)), len(lines))
                    if end - i > MAX_SUBCKT_LINES:
                        problems.append(f"large .subckt ({end - i} lines) in {path.relative_to(ROOT)}: vendor model text?")
                if re.match(r"\s*\.model\b", line, re.I) and line.count("=") > MAX_MODEL_PARAMS:
                    problems.append(f"large .model card in {path.relative_to(ROOT)}: vendor model text?")


def run_self_tests(problems: list[str]) -> list[str]:
    ran = []
    for script in sorted(SKILLS.glob("*/scripts/*.py")):
        if "--self-test" not in script.read_text(encoding="utf-8", errors="replace"):
            continue
        for flags in ([], ["-O"]):
            run = subprocess.run([sys.executable, *flags, str(script), "--self-test"], capture_output=True, text=True,
                                 timeout=600)
            label = f"{script.relative_to(ROOT)}{' (-O)' if flags else ''}"
            ran.append(label)
            if run.returncode != 0:
                tail = (run.stdout + run.stderr).strip().split("\n")[-5:]
                problems.append(f"self-test failed: {label}: " + " | ".join(tail))
    return ran


def main() -> int:
    problems: list[str] = []
    skills = sorted(p for p in SKILLS.iterdir() if (p / "SKILL.md").is_file())
    for skill in skills:
        check_frontmatter(skill, problems)
        check_agent_yaml(skill, problems)
    links = check_links(problems)
    check_leaks(problems)
    ran = run_self_tests(problems)
    for p in problems:
        print("FAIL:", p)
    print(f"{len(skills)} skills, {links} relative links, {len(ran)} self-test runs: "
          + ("ALL CHECKS PASSED" if not problems else f"{len(problems)} PROBLEMS"))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
